LANGUAGES = ["en-US", "zh-CN", "fr-FR", "ja-JP", "en-GB"]

LAN_MAPS = {
    "en-US": "美式英语",
    "en-GB": "英式英语",
    "zh-CN": "简体中文",
    "ja-JP": "日语",
    "fr-FR": "法语",
}

CEFR_LEVEL_MAPS = {
    "A1": "入门级",
    "A2": "初级",
    "B1": "中级",
    "B2": "中高级",
    "C1": "高级",
    "C2": "母语级",
}

FAKE_EMAIL_DOMAIN = "example.com"


TOPICS = {
    "en-US": [
        "Current events",
        "Social issues",
        "Science and technology",
        "History and culture",
        "Arts and entertainment",
        "Personal experiences",
        "Work and education",
        "Food and travel",
        "Sports and hobbies",
        "Family and friends",
        "Health and fitness",
        "Business and finance",
        "The environment",
    ],
    "zh-CN": [
        "时事问题",
        "社会问题",
        "科学技术",
        "历史文化",
        "艺术和娱乐",
        "个人经历",
        "工作与教育",
        "美食和旅行",
        "运动和爱好",
        "亲朋好友",
        "健康和健身",
        "商业和金融",
        "环境",
    ],
    "fr-FR": [
        "Actualités",
        "Problèmes sociaux",
        "Science et technologie",
        "Histoire et culture",
        "Les arts et le divertissement",
        "Expériences personnelles",
        "Travail et Education",
        "Nourriture et voyages",
        "Sports et loisirs",
        "Famille et amis",
        "Santé et remise en forme",
        "Entreprise et finance",
        "L'environnement",
    ],
    "ja-JP": [
        "時事問題",
        "社会問題",
        "科学技術",
        "歴史と文化",
        "芸術とエンターテイメント",
        "個人的な経験",
        "仕事と教育",
        "食と旅",
        "スポーツと趣味",
        "家族と友達",
        "健康と運動",
        "ビジネスと金融",
        "環境",
    ],
}

NAMES = {
    "zh-CN": {
        "男性": ["浩然", "子轩", "皓轩", "梓浩", "浩宇", "宇轩", "亦辰", "宇辰", "宇航", "子墨"],
        "女性": ["一诺", "依诺", "欣怡", "梓涵", "诗涵", "欣妍", "可欣", "语汐", "雨桐", "梦瑶"],
    },
    "en-US": {
        "male": [
            "Michael",
            "David",
            "John",
            "Ethan",
            "Daniel",
            "Elijah",
            "Alexander",
            "Matthew",
            "Joseph",
            "William",
        ],
        "female": [
            "Ava",
            "Olivia",
            "Emma",
            "Sophia",
            "Isabella",
            "Mia",
            "Abigail",
            "Evelyn",
            "Charlotte",
            "Emily",
        ],
    },
    "fr-FR": {
        "mâle": [
            "Gabriel",
            "Léo",
            "Raphaël",
            "Louis",
            "Arthur",
            "Noah",
            "Malo",
            "Mae",
            "Elio",
            "Nino",
        ],
        "femelle": [
            "Jade",
            "Louise",
            "Emma",
            "Ambre",
            "Alice",
            "Alba",
            "Ava",
            "Alma",
            "Iris",
            "Romy",
        ],
    },
    "ja-JP": {
        "男": ["翔太", "悠仁", "蓮", "湊", "楓", "大翔", "颯太", "悠真", "湊翔", "優斗"],
        "女": ["凛", "結衣", "紬", "杏", "結衣", "葵", "凜", "結菜", "心愛", "結愛"],
    },
}

PROVINCES = [
    "辽宁",
    "吉林",
    "黑龙江",
    "北京",
    "天津",
    "河北",
    "山西",
    "内蒙古自治区",
    "上海",
    "江苏",
    "浙江",
    "安徽",
    "福建",
    "江西",
    "山东",
    "河南",
    "湖北",
    "湖南",
    "广东",
    "重庆",
    "四川",
    "贵州",
    "云南",
    "西藏自治区",
    "陕西",
    "甘肃",
    "青海",
    "新疆维吾尔自治区",
    "香港特别行政区",
    "澳门特别行政区",
    "台湾",
]
